function [] = plot3dWriter(filename, block)
% Writes a block-based grid, of the form generated by plot3dReader, to a plot3d file

fid = fopen(filename, 'w+');
try
nBlocks = block(1).nBlocks;
catch
    nBlocks = numel(block);
end
fprintf(fid, '%i \n', nBlocks);

if iscell(block)
%     block2 = struct(size(block));



for i = 1:nBlocks
    [block{i}.I block{i}.J block{i}.K] = size(block{i}.x);
    block2(i).I = block{i}.I;
    block2(i).J = block{i}.J;
    block2(i).K = block{i}.K;
    if isfield(block{i},'y')
        block2(i).x = block{i}.x;
        block2(i).y = block{i}.y;
        block2(i).z = block{i}.z;
        
    else
        block2(i).x = block{i}.x;
        block2(i).rt = block{i}.rt;
        block2(i).r = block{i}.r;
    end
end
block = block2;
end

for i = 1:nBlocks
    fprintf(fid, '%i ', block(i).I);
    fprintf(fid, '%i ', block(i).J);
    fprintf(fid, '%i ', block(i).K);
end

fprintf(fid, '\n');
%  save test
count = 1;
for m = 1:nBlocks

    if ~isfield(block(m),'y') || isempty(block(m).y)
        [block(m).y block(m).z] = pol2cart(block(m).rt./block(m).r,block(m).r);
        inan = isnan(block(m).y);
        block(m).y(inan) = 0;
        block(m).z(inan) = 0;
    end
    
    A = zeros(1,3*block(m).I*block(m).J*block(m).K);
   
    count  = 1;
    for k = 1:block(m).K
        for j = 1:block(m).J
            for i = 1:block(m).I
                A(count) = block(m).x(i,j,k);
                count = count+1;
            end
        end
    end
    for k = 1:block(m).K
        for j = 1:block(m).J
            for i = 1:block(m).I
                A(count) = block(m).y(i,j,k);
                count = count+1;
            end
        end
    end
    for k = 1:block(m).K
        for j = 1:block(m).J
            for i = 1:block(m).I
                A(count) = block(m).z(i,j,k);
                count = count+1;
            end
        end
    end

    fprintf(fid,'%.12e ',A);
    fprintf(fid,'\n');
end

fclose(fid);
%{
% for i = 1:nBlocks
%     block(i).I = A(2+(i-1)*3);
%     block(i).J = A(3+(i-1)*3);
%     block(i).K = A(4+(i-1)*3);
%     block(i).x = zeros(block(i).I,block(i).J,block(i).K);
%     block(i).y = block(i).x;
%     block(i).z = block(i).x;
% end
%
% A = A(3*nBlocks+2:size(A,1));
%
% count = 1;
% for m = 1:nBlocks
%     for i = 1:block(m).I
%         for j = 1:block(m).J
%             for k = 1:block(m).K
%                 block(m).x(i,j,k) = A(count);
%                 count = count+1;
%             end
%         end
%     end
%     for i = 1:block(m).I
%         for j = 1:block(m).J
%             for k = 1:block(m).K
%                 block(m).y(i,j,k) = A(count);
%                 count = count+1;
%             end
%         end
%     end
%     for i = 1:block(m).I
%         for j = 1:block(m).J
%             for k = 1:block(m).K
%                 block(m).z(i,j,k) = A(count);
%                 count = count+1;
%             end
%         end
%     end
% end
%}